# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:10.15.3

pipelines:
  default:
    - parallel:
      - step:
          name: Install, Unit tests, Build
          caches:
           - node
          deployment: test
          script:
           - npm install
           - >
             wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - && \
               sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' && \
               apt-get update && \
               apt-get install -y google-chrome-stable xvfb procps       
           - npm run test:ci
           - npm run build:prod
